<a href="https://colab.research.google.com/github/chandrateja85/Pandas_basics_python/blob/main/NumpyCrashCourse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import numpy as np

In [2]:
import numpy as np

In [3]:
mylist=[0,1,2,3,4]
mylist


[0, 1, 2, 3, 4]

In [4]:
array=np.array(mylist)
array

array([0, 1, 2, 3, 4])

In [5]:
np.arange(5)  #To arrange the elements in an array

array([0, 1, 2, 3, 4])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3,5)

array([3, 4])

In [9]:
np.zeros(5,5)

TypeError: ignored

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.random.randint(0,10)

In [14]:
np.random.randint(10,20)

13

In [15]:
np.random.randint(0,10,(4,4))

array([[3, 1, 4, 7],
       [7, 5, 2, 2],
       [1, 4, 3, 4],
       [6, 4, 3, 2]])

In [16]:
np.random.randint(0,10,10)# the 0 ,10 denotes the range and last 10 denotes the number of random integers need to be generated

array([7, 4, 4, 8, 2, 1, 2, 5, 4, 0])

In [17]:
np.random.seed(12)
ar=np.random.randint(0,20,10)  #np.random.seed() function will fix the random values generated at the first time from then onwards if we execute any number of times it results the same random values
ar

array([11,  6, 17,  2,  3,  3, 12, 16, 17,  5])

In [18]:
ar.max()

17

In [19]:
ar.min()

2

In [20]:
ar.mean()

9.2

In [21]:
ar.median() # we cant find the median

AttributeError: ignored

In [22]:
ar.reshape(2,5)  # 10 values to 2 rows

array([[11,  6, 17,  2,  3],
       [ 3, 12, 16, 17,  5]])

In [23]:
ar.reshape(10,1)

array([[11],
       [ 6],
       [17],
       [ 2],
       [ 3],
       [ 3],
       [12],
       [16],
       [17],
       [ 5]])

In [24]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [25]:
rows=4
cols=3

In [26]:
mat[3,2]

32

In [27]:
mat[rows,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

**Masking**

In [29]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [31]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [30]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
matrix=np.arange(0,20)
matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
matrix=np.reshape(matrix,(4,5))
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [9]:
matrix=np.reshape(matrix,(5,4),order='f' )
matrix


array([[ 0,  6, 12, 18],
       [ 5, 11, 17,  4],
       [10, 16,  3,  9],
       [15,  2,  8, 14],
       [ 1,  7, 13, 19]])

In [10]:
matrix=np.arange(0,20)
matrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
matrix=np.reshape(matrix,(5,4),order='f' )
matrix


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [12]:
matrix[0:3]

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17]])